VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  config.vm.provision "file", source: ".", destination: "/opt/pokkit"
  config.vm.provision "shell", path: "provisions/install.sh"
end
